<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Authors>John Korsnes</Authors>
    <Description>This is a sample classlib published via the template repo</Description>
    <PackageTags>library</PackageTags>
    <PackageIcon>icon.512x512.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <License>LICENSE</License>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/johnkors/dotnet-library</PackageProjectUrl>
    <RepositoryUrl>https://github.com/johnkors/dotnet-library</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <DotNet9Version>9.0.0</DotNet9Version>
    <DotNet10Version>10.0.0</DotNet10Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotNet9Version)" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(DotNet9Version)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(DotNet9Version)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotNet10Version)" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(DotNet10Version)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(DotNet10Version)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../images/icon.512x512.png" Pack="true" PackagePath="" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomePeerDependency\SomePeerDependency.csproj" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeP2PAssets</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>
  <Target Name="IncludeP2PAssets">
    <ItemGroup>
        <BuildOutputInPackage Include="$(OutputPath)SomePeerDependency.dll" />
    </ItemGroup>
</Target>

</Project>
